### PR TITLE
feat: left align text fieds of container block

### LINKED ISSUE #39: [NEW FEATURE] container name should be left-aligned
I'd wish container name would be left aligned in the "Containers" table.

image

This happens regularly when using docker compose.

### PR DESCRIPTION
**Pull request by aljazerzen**
Closes #39

I've left-aligned a few non-numerical text fields in container section (container name, status and image name). I really care only about container name.

### CODE REVIEW

**Comment by aljazerzen** [comment]
I've fixed the tests. I think they could be improved by using [insta](https://docs.rs/insta/latest/insta/), where one can easily accept newly generated text as the expected string.

**Comment by mrjackwills** [comment]
I think the columns and widths need some work, I've had a play around left aligning everything, and it looks decent, probably better than as it is currently. 

Plus there were a couple mistakes with the widths of the headers and it's corresponding header, and probably a load of pointless calculations that we can get rid of

**Comment by aljazerzen** [comment]
This looks great, I'll add it to this PR.

I've also opened a pull request that uses insta in tests, so that will make fixing test here much easier.

**Comment by mrjackwills** [comment]
I did forget to update the tests, but I can sort that out

**Pull request merged**
